logging:
  config: classpath:logback/logback-dev.xml

spring:
  datasource:
    dynamic:
      datasource:
        # 系统管理数据源 - 开发环境
        system:
          url: jdbc:mysql://10.10.26.212:3306/framework?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&tinyInt1isBit=false
          username: root
          password: Hs@2025.tz.com
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            minimum-idle: 0
            maximum-pool-size: 20
            idle-timeout: 10000
            auto-commit: true
            connection-test-query: SELECT 1
        # 支付模块数据源 - 开发环境
#        pay:
#          url: jdbc:mysql://10.10.26.212:3306/sandy_pay?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&tinyInt1isBit=false
#          username: root
#          password: Hs@2025.tz.com
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          hikari:
#            minimum-idle: 0
#            maximum-pool-size: 20
#            idle-timeout: 10000
#            auto-commit: true
#            connection-test-query: SELECT 1
  redis:
    host: 10.10.26.212
    port: 6379
    password: 123456
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
